const mongoose=require('mongoose');
const productSchema=new mongoose.Schema({
    productName:{
        type:String,
        required:true,
    },
    image:{
        type:Array,
        required:true
    },
    description:{
        type:String,
        max:100,
    },
    category:{
        type:String,
        ref:'category',
        required:true
    },
    price:{
        type:Number,
        required:true,
    },
    size:{
        type:Number,
        required:true,
    },
    stock:{
        type:Number,
        required:true
    },
    status:{
        type:String,
        default:"Unlisted",   
    }
    })
    module.exports=productModel=mongoose.model('products',productSchema)